### ISSUE TITLE
[enhancement]

### ISSUE THREAD

**Issue by Niggolo** [LorenzoPane/browserdefault#1]
make it work with link from mail app

**Comment by LorenzoPane** [comment]
>make it work with link from mail app

@Niggolo Thanks for pointing this out.  I’m currently looking into this.  It seems like the mail app is overriding the method that I hook in it’s parent, UIApplication.  I could easily add support for the mail app specificity, but that wouldn’t be very future-proof because this bug is indicative of a flaw that has the potential to remove compatibility in any number of apps.  I’m looking into a way to either hook overridden methods of a children of a superclass, or implement my hook at a lower level by finding out what the overridden methods are calling.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Niggolo** [comment]
Nice it work! But just let you know, after the update the config was reset to default (I just had to reselect the browser)
