### ISSUE TITLE
Whatsapp & mail app

### ISSUE THREAD

**Issue by Niggolo** [LorenzoPane/browserdefault#14]
When I click a link from WhatsApp it open an empty page on Mozilla Firefox
It also happening with the mail app

Using 1.8.4, iPhone 7+, 12.1.2.

**Comment by barak0** [comment]
Yeah and when i click alink in the mail it google search the link

**Comment by LorenzoPane** [comment]
I'll take a look when I get home.

**Comment by Niggolo** [comment]
I’m having this problem again!
Default browser: 1.9.1, uncover 3.1.3, i7+ 12.1.2

I tried it with all other tweak disabled and it still not working

**Comment by LorenzoPane** [comment]
Did you download 1.9.0 from GitHub or Packix?

**Comment by Niggolo** [comment]
About the message you removed, I used cydia downgrade anyway 💪🏻

**Comment by LorenzoPane** [comment]
Should be fixed in 1.9.2.  You can get the deb [here](https://github.com/LorenzoPane/browserdefault/blob/master/StableBuilds/com.lpane.browserdefault_1.9.2_iphoneos-arm.deb?raw=true) or wait for it to be updated on Packix tomorrow.

**Comment by barak0** [comment]
Thanks a lot.

**Comment by Niggolo** [comment]
Thank you!

**Comment by Niggolo** [comment]
Btw still not working 🙄

**Comment by LorenzoPane** [comment]
It's working for me, but I'm looking into trying to reproduce it.  Sorry :/

**Comment by Niggolo** [comment]
Let me know if I can give you some log or anything

**Comment by LorenzoPane** [comment]
I. Am. A. Complete. Buffoon.  I was using Firefox-Focus rather than Firefox.  The issue should be fixed in [1.9.3](https://github.com/LorenzoPane/browserdefault/blob/master/StableBuilds/com.lpane.browserdefault_1.9.3_iphoneos-arm.deb?raw=true).  Today ain't my day.

Thanks for putting up with this shit, and let me know if there are still issues you run into.  I haven't been putting much time into this particular project, and I haven't been paying close enough attention monitoring the quality of the updates as I probably should.

**Comment by Niggolo** [comment]
I can confirm it work! Anyway don’t worry, this tweak is really useful but it is still free, so you are not forced to keep it update or even having fun while working on it 👌🏻
